
[book]
title = "数据结构与算法 Rust 语言实现"
authors = ["Shaohua <shaohua@biofan.org>"]
description = ""
src = "book"
language = "zh_CN"

[rust]
edition = "2021"

[build]
build-dir = "book-out"
#create-missing = false

[output.html]
git-repository-url = "https://github.com/xushaohua/TheAlgorithms"
