
[workspace]
resolver = "2"

members = [
  "bitwise",
  "conversions",
  "deque",
  "graph",
  "hash_table",
  "leetcode/0*.*",
  "leetcode/1*.*",
  "leetcode/2*.*",
  "list",
  "priority_queue",
  "queue",
  "search",
  "sort",
  "stack",
  "string",
  "tree",
  "vector",
]

[profile.release]
debug = true
lto = true
