
[workspace]
resolver = "2"

members = [
  "bit_manipulation",
  "boolean_gates",
  "conversions",
  "data_structures",
  "electronics",
  "financial",
  "geodesy",
  "leetcode/*.*",
  "math",
  "physics",
  "searches",
  "sorts",
  "graphs",

# Custome
  "leetcode/*.*",
]

exclude = [
  "project_euler",
]


[profile.release]
debug = true
lto = true
