
[workspace]
resolver = "2"

members = [
  "bit_manipulation",
  "boolean_gates",
  "conversions",
  "ds",
  "electronics",
  "financial",
  "geodesy",
  "leetcode/*.*",
  "math",
  "physics",
  "robert",
  "weiss/c02",
]

exclude = [
  "project_euler",
]


[profile.release]
debug = true
lto = true
