[package]
name = "array"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "reverse"
harness = false

[[bench]]
name = "rotate"
harness = false
