[package]
name = "bit_manipulation"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "count_ones"
harness = false

[[bench]]
name = "trailing_zeros"
harness = false
